import { Header } from "../components/header/Header.jsx";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light"  style={{colorScheme: "light"}}>
      <body className={inter.className + " bg-bc dark:bg-n"}>
        <Providers>
          <main className="min-h-screen p-2 max-w-7xl m-auto  bg-bc dark:bg-n">
          <Header />
            {children}
          </main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
