import { Header } from "../components/header/Header.jsx";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./Providers.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" 
    className="light"  style={{colorScheme: "light"}}
    >
      <body className={inter.className + " bg-bc dark:bg-n"}>
        <Providers>
          <Header />
            {children}
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
